""""Implement_core_models_with_UUID_keys"

Revision ID: 6139a02d9ff2
Revises: fe844f5670e5
Create Date: 2025-12-10 00:24:54.267907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6139a02d9ff2'
down_revision: Union[str, None] = 'fe844f5670e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('ix_api_keys_id', table_name='api_keys')
    op.create_unique_constraint(None, 'api_keys', ['key_hash'])
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('type', sa.Enum('DEPOSIT', 'TRANSFER', name='transactiontype'), nullable=False))
    op.add_column('transactions', sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='transactionstatus'), nullable=False))
    op.alter_column('transactions', 'reference',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_constraint('transactions_sender_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_recipient_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'sender_wallet_id')
    op.drop_column('transactions', 'recipient_wallet_id')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_wallets_id', table_name='wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_wallets_id', 'wallets', ['id'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.add_column('transactions', sa.Column('recipient_wallet_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_recipient_wallet_id_fkey', 'transactions', 'wallets', ['recipient_wallet_id'], ['id'])
    op.create_foreign_key('transactions_sender_wallet_id_fkey', 'transactions', 'wallets', ['sender_wallet_id'], ['id'])
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'reference',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'user_id')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.create_index('ix_api_keys_id', 'api_keys', ['id'], unique=False)
    op.alter_column('api_keys', 'permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
